version: 'latest'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

volumes:
  mysql-data:


